# 把本文件放到 ~/.config/clangd/config.yaml
CompileFlags:
  Add:
    - --no-cuda-version-check
    - -Wno-unknown-warning-option
    - -D__clangd__  # 添加你的自定义选项
  Remove:
    - -mlongcalls
    - -fno-shrink-wrap
    - -fno-tree-switch-conversion
    - -fstrict-volatile-bitfields
    - -mfix-esp32-psram-cache-issue
    - -forward-unknown-to-host-compiler
    - -expt-*
    - --expt-*
    - -gencode*
    - --generate-code*
    - -Xfatbin*
    - -arch=*
    - -rdc=*
    - -mno-*
InlayHints:
  ParameterNames: Yes
  DeducedTypes: Yes
